site_name: V-Insight R&D Knowledge Base
site_url: https://team-vinsight.github.io/knowledge-base/
site_description: RnD Knowledge Base for Deep Learning-Powered Visual SLAM Project
repo_url: https://github.com/team-vinsight/knowledge-base
repo_name: team-vinsight/knowledge-base

theme:
  name: readthedocs
  logo: assets/logo.png
  collapse_navigation: true
  sticky_navigation: true


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - Home: index.md
  - Project Info:
    - Tech Stack: tech-stack.md
  - Research:
    - Literature Review: literature.md
    - VSLAM Models: vslam/
  - Hardware: hardware/
  - Datasets: datasets.md
